/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppSidebar: typeof import('./src/components/layout/AppSidebar.vue')['default']
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    CompanyFormDialog: typeof import('./src/components/company/CompanyFormDialog.vue')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('primevue/sidebar')['default']
    SidebarAside: typeof import('primevue/sidebaraside')['default']
    SidebarBackdrop: typeof import('primevue/sidebarbackdrop')['default']
    SidebarContent: typeof import('primevue/sidebarcontent')['default']
    SidebarGroup: typeof import('primevue/sidebargroup')['default']
    SidebarGroupContent: typeof import('primevue/sidebargroupcontent')['default']
    SidebarGroupLabel: typeof import('primevue/sidebargrouplabel')['default']
    SidebarHeader: typeof import('primevue/sidebarheader')['default']
    SidebarLayout: typeof import('primevue/sidebarlayout')['default']
    SidebarMain: typeof import('primevue/sidebarmain')['default']
    SidebarMenu: typeof import('primevue/sidebarmenu')['default']
    SidebarMenuButton: typeof import('primevue/sidebarmenubutton')['default']
    SidebarMenuItem: typeof import('primevue/sidebarmenuitem')['default']
    SidebarPanel: typeof import('primevue/sidebarpanel')['default']
    SidebarTrigger: typeof import('primevue/sidebartrigger')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
  }
}
